### ISSUE TITLE
AttributeError: 'function' object has no attribute 'iter_fields'

### ISSUE THREAD

**Issue by ccorcos** [mitsuhiko/jinja2#536]
I'm pretty new to Jinja, still trying to figure out what this means:

```haskell
Traceback (most recent call last):
  File "build_preview.py", line 239, in <module>
    write(name+'_html.html', inline_css(render_jinja(get_text(msg, 'html'))))
  File "build_preview.py", line 234, in render_jinja
    return Template(text).render(**filters)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 926, in __new__
    return env.from_string(source, template_class=cls)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 862, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 553, in compile
    source = optimize(source, self)
  File "/Library/Python/2.7/site-packages/jinja2/optimizer.py", line 27, in optimize
    return optimizer.visit(node)
  File "/Library/Python/2.7/site-packages/jinja2/visitor.py", line 39, in visit
    return self.generic_visit(node, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/jinja2/visitor.py", line 59, in generic_visit
    for field, old_value in node.iter_fields():
AttributeError: 'function' object has no attribute 'iter_fields'
```

Similar to https://github.com/mitsuhiko/jinja2/issues/396

**Comment by ccorcos** [comment]
Well I called render with a function, lol. Now that makes sense
